title: ACS Documentation
description: Work In Progress
remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs

url: https://rit-construct-makerspace.github.io/access-control-documentation

aux_links:
  SHED Makerspace Home: https://make.rit.edu
