title: ACS Documentation
description: Work In Progress
theme: just-the-docs

url: https://rit-construct-makerspace.github.io/access-control-documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
