title: ACS Documentation
description: Work In Progress
remote_theme: carlosperate/jekyll-theme-rtd

url: https://rit-construct-makerspace.github.io/access-control-documentation

edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
